name: inception
services:
  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - wordpress_data:/var/www/${DOMAIN_NAME}
    environment:
      - DOMAIN_NAME=$DOMAIN_NAME
    secrets:
      - nginx_crt
      - nginx_key
    networks:
     - inception
    restart: always
  
  mariadb:
    build:
      context: mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      - DOMAIN_NAME=$DOMAIN_NAME
    secrets:
      - mariadb_database
      - mysql_root_password
      - mysql_user
      - mysql_user_password
    healthcheck:
      test: ["CMD","mariadb-admin","ping","-h","localhost"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 20s
    networks:
     - inception
    restart: always

  wordpress:
    build:
      context: wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    volumes:
      - wordpress_data:/var/www/${DOMAIN_NAME}
    environment:
      - DOMAIN_NAME=$DOMAIN_NAME
    secrets:
      - mariadb_database
      - mysql_user
      - mysql_user_password
      - wp_admin_user
      - wp_admin_password
      - wp_admin_email
      - wp_user
      - wp_user_password
      - wp_user_email
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
     - inception
    restart: always

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/${USER}/data/mariadb'
  wordpress_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/${USER}/data/wordpress'

secrets:
  nginx_crt:
    file: ${CERT_DIR}/nginx.crt
  nginx_key:
    file: ${CERT_DIR}/nginx.key
  mariadb_database:
    file: ${SECRET_DIR}/mariadb_database.secrets
  mysql_root_password:
    file: ${SECRET_DIR}/mysql_root_password.secrets
  mysql_user:
    file: ${SECRET_DIR}/mysql_user.secrets
  mysql_user_password:
    file: ${SECRET_DIR}/mysql_user_password.secrets
  wp_admin_user:
    file: ${SECRET_DIR}/wp_admin_user.secrets
  wp_admin_password:
    file: ${SECRET_DIR}/wp_admin_password.secrets
  wp_admin_email:
    file: ${SECRET_DIR}/wp_admin_email.secrets
  wp_user:
    file: ${SECRET_DIR}/wp_user.secrets
  wp_user_password:
    file: ${SECRET_DIR}/wp_user_password.secrets
  wp_user_email:
    file: ${SECRET_DIR}/wp_user_email.secrets

networks:
  inception:
    driver: bridge

