services:
  nginx:
    image: nginx
    build:
      context: nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "8443:443"
#    volumes:
#    config:
#    secrets:
#    environment:
    networks:
     - inception
#    depends_on:
#      - site

networks:
  inception:
    driver: bridge
