events {}

http {
    resolver 127.0.0.11 valid=30s ipv6=off;
    resolver_timeout 5s;

    server {
		listen 80;
		listen [::]:80;
		server_name stempels.42.fr;
		return 301 https://$host:443$request_uri;
    }

    server {

        listen 443 ssl;
        server_name $DOMAIN_NAME;

		ssl_certificate	    /run/secrets/nginx_crt;
		ssl_certificate_key /run/secrets/nginx_key;
		ssl_protocols	    TLSv1.2 TLSv1.3;

        root /var/www/stempels.42.fr;
        index index.php index.html;

		location / {
          try_files $uri $uri/ /index.php?$args;
		}

        location ~\.php$ {
			try_files $uri =404;

			set $upstream_var wordpress;
    		resolver 127.0.0.11 valid=30s ipv6=off;
        	fastcgi_pass $upstream_var:9000;

          	include fastcgi_params;

			fastcgi_index index.php;

          	fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
          	fastcgi_param PATH_INFO $fastcgi_path_info;
#          	fastcgi_split_path_info ^(.+\.php)(/.+)$;

			fastcgi_connect_timeout 5;
			fastcgi_send_timeout 30s;
			fastcgi_read_timeout 30s;
        }

		location ~ /\. {
			deny all;
		}
    }
}
