events {}

http {
    resolver 127.0.0.11 valid=30s ipv6=off;
    resolver_timeout 5s;

    server {
        listen 80;
	listen [::]:80;
	server_name $DOMAIN_NAME;
	return 301 https://$host:443$request_uri;
    }

    server {

        listen 443 ssl;
        server_name $DOMAIN_NAME;

	ssl_certificate	    /run/secrets/nginx_crt;
	ssl_certificate_key /run/secrets/nginx_key;
	ssl_protocols	    TLSv1.2 TLSv1.3;

	set $upstream_var wordpress;
	resolver 127.0.0.11 valid=30s;
        proxy_pass http://$upstream_var:9000;

        root /var/www/$DOMAIN_NAME;
        index index.php;

	location / {
          try_files $uri $uri/ =404;
	}

        location ~\.php$ {
          fastcgi_split_path_info ^(.+\.php)(/.+)$;
          fastcgi_pass wordpress:9000;
          include fastcgi_params;
          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
          fastcgi_param PATH_INFO $fastcgi_path_info;
        }
    }
}
